### PR TITLE
Remember map extent #50 [Added functionality]

### LINKED ISSUE #50: Remember map extent
We should do the same as most map apps and remember the last extent when visiting the website. It's safe to just put it in the local browser store IMO. Smth we might want to do for more info than just extent, e.g. last used costing model?

### PR DESCRIPTION
**Pull request by harsh5902**
Closes #50 

## 🛠️ Fixes Issue
used localstorage of the user to remember the mapextent

## 👨‍💻 Changes proposed

If user moves his/her pointer on the map and moves to new location then localstorage will store his session and next time when he/she starts the app will get the same location where they left before.

You can see the center latitude and longitude on the developer tools application tab
## 📷 Screenshots

image

### CODE REVIEW

**Review by nilsnolde — COMMENTED** [review]
Thanks! I'd consolidate it to a coordinate and not split up lat & lon when storing it in localstorage. Also we should capture the zoom as well as the center coordinate.

Can we name the localstorage items `last_center` & `last_zoom`?

**Comment by harsh5902** [comment]
Sure I will make the necessary changes as needed

**Comment by harsh5902** [comment]
@nilsnolde I have made the necessary changes you pointed out and also used localstorage for zoom level as well

image

**Comment by nilsnolde** [comment]
LGTM, thanks!

**Pull request merged**
