### PR TITLE
Fix error when displaying heightgraph without waypoints

### LINKED ISSUE #166: Adding Warnings (Height-Graph/ Draw Text)
### What is the problem you are facing

currently, height-graph feature is displaying an error message when it is used without a selected route. 
Even some sort of compilation error comes when we use Draw Text.

### What is your suggested solution

It should not display an compilation error message. Instead, it should display a warning message to select a route first.

### Screenshots

https://user-images.githubusercontent.com/112114562/229269293-0931e323-16eb-4d75-831b-2ba9b796df33.mp4

### PR DESCRIPTION
**Pull request by Sheikh-JamirAlam**
## 🛠️ Fixes Issue
Fixes  #166 

## 👨‍💻 Changes proposed

- Added warning notification when trying to display heightgraph without any waypoints selected.
- No errors when adding DrawText

## 📄 Note to reviewers
Please take a look at the screenshots in the comments as well.

## 📷 Screenshots

https://user-images.githubusercontent.com/48979376/229411999-f67a7fe3-daf9-4c54-88ea-638d8b6ea0fb.mp4

### CODE REVIEW

**Comment by Sheikh-JamirAlam** [comment]
## 📷 Screenshots

https://user-images.githubusercontent.com/48979376/229490579-a5536ffa-75b0-47b2-aa9a-35f99451789c.mp4

**Comment by Sheikh-JamirAlam** [comment]
@nilsnolde Can you review this please?

**Comment by nilsnolde** [comment]
Can we either first move entirely to react-toastify or revert the relevant changes here and use the old package?

**Comment by nilsnolde** [comment]
Other than that, I think that looks fine!

**Comment by Sheikh-JamirAlam** [comment]
@nilsnolde Does this look good? Shall I commit the changes?

https://user-images.githubusercontent.com/48979376/229614804-4f110c6d-7034-42a8-aa2d-210570ff2773.mp4

**Comment by Sheikh-JamirAlam** [comment]
@nilsnolde Alright sure!

**Pull request closed without merging**
