### PR TITLE
Removed the via waypoint by default

### PR DESCRIPTION
**Pull request by inceptionabhishek**
When the app loads we have 3 waypoints ( **Destination**, **Origin**, and **Via** ). 

So, the via waypoint can be intentionally added by the user using the + Icon on the bottom of the sidebar.

ScreenShot : 
image
For removing the additional via waypoint I changed the value of amount from 3 to 2 when the component first mounted.

### CODE REVIEW

**Comment by inceptionabhishek** [comment]
@nilsnolde please review this pull request. Thanks.

**Comment by nilsnolde** [comment]
No comments in the code obviously!

**Comment by inceptionabhishek** [comment]
@nilsnolde ok, I have removed the console log from the file. Please review it. Thanks.

**Comment by nilsnolde** [comment]
When I have time, I'll run all of these PR's locally.

**Review by nilsnolde — APPROVED** [review]

**Pull request merged**
