### PR TITLE
fixes Inconsistent height graph coloring #57

### LINKED ISSUE #57: Inconsistent height graph coloring
https://valhalla.openstreetmap.de/directions?profile=bicycle&wps=13.376197814941408%2C52.547776790183214%2C13.38589668273926%2C52.55713840780446%2C13.393707275390627%2C52.5650153081717%2C13.390789031982424%2C52.56655304975672%2C13.389244079589846%2C52.57029962885746

In many cases, elevation change and steepness are contradicting, see this example:
grafik

### PR DESCRIPTION
**Pull request by Binabh**
## 🛠️ Fixes Issue

Closes #57 

## 👨‍💻 Changes proposed

- new approach in building the geojson so that the inconsistency in coloring in height graph is removed

## 📄 Note to reviewers

Please let me know if any changes/improvements required

## 📷 Screenshots

checked on [this](https://github.com/gis-ops/valhalla-app/issues/57#issue-1573894591) case

image

checked on [this](https://github.com/gis-ops/valhalla-app/issues/57#issuecomment-1428556845) case
image

### CODE REVIEW

**Review by nilsnolde — COMMENTED** [review]
Ah nice! That's a very long-standing issue and been bothering quite a bit (though apparently not to the point to attempt a fix..). Thanks a lot @Binabh, looks good! 

Just one further ask: could you leave some comments in the code what this does? I know there were no comments before either, but that's also bothering. The logic is not apparent to me tbh, e.g. what `attributeType` does and why we're pushing the same coordinates twice if the heighClass changed. I'm also lacking the context without looking into the code and see what the heigh graph package needs and does. So for reviewing it'd be much more convenient to read a comment what it does to give the context. Hope that makes sense.

**Comment by Binabh** [comment]
sure @nilsnolde I will try to explain the best I can and best I have understood. I will be adding commit with comments in few hours.
Thank You for your suggestion and review !

**Comment by Binabh** [comment]
@nilsnolde I have tried to add some explanation. I have to admit that documentation is not my strong part. I further explain any particular line if required.

Also, one major difference between previous and current code is that previously we were making new linestrings if current heightClass is different than previous but what we actually needed to do is end current linestring and start a new one as soon as we see change in height class. Hope this makes sense.

**Review by nilsnolde — APPROVED** [review]
Right, it's not super well written tbh, but it's really ok, I understand it now better for sure, thanks. I'd generally try to work a bit more on docs skills, it's really important for devs IMO, it makes for much more seamless collaboration with others. And remember to annotate/comment your PRs for any non-trivial things to put context for reviewers, I'm always very happy to see that so it's less time for me to review:)

Anyways, I'm really grateful you solved this! And IMO pretty elegantly, pretty much without any additional lines, I like that very much:)

**Comment by Binabh** [comment]
Sure, @nilsnolde thank you for your suggestion.
Also thank you for the review/merge and this awesome project.

**Pull request merged**
